FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# olajuwon99


## User [/user]

### List All Users [GET]

+ Response 200 (application/json)

        [
            {
                "_id": "string",
                "dateOfBirth": "2018-05-23T04:51:40.862Z",
                "realm": "string",
                "username": "string",
                "credentials": {},
                "challenges": {},
                "email": "string",
                "emailVerified": true,
                "status": "string",
                "created": "2018-05-23T04:51:40.862Z",
                "lastUpdated": "2018-05-23T04:51:40.862Z",
                "locationRef": "string",
                "_lmt": "2018-05-23T04:51:40.862Z",
                "_ect": "2018-05-23T04:51:40.862Z",
                "_tenantRef": "string"
            }
        ]


### Create a New User [POST]

You may create your own user using this action. It takes a JSON
object containing user details and under which security group it's in.

+ Request (application/json)

        {
            "first_name": "Hakeem",
            "last_name": "Olajuwon",
            "email": "olajuwon99@houston.com",
            "username": "olajuwon99@houston.com",
            "password": "123456",
            "language": "en",
            "groups": ["houston", "toronto"],
            "tags": ["The Dream", "Hakeem the Dream Olajuwon"],
            "client_role": "Advisor"
        }

+ Response 200 (application/json)


    + Body

            {
                "_id": "uuid",
                "username": "olajuwon99@houston.com",
                "email": "olajuwon99@houston.com",
                "created": "2018-05-23T04:51:40.862Z",
                "lastUpdated": "2018-05-23T04:51:40.862Z",
                "_lmt": "2018-05-23T04:51:40.862Z",
                "_ect": "2018-05-23T04:51:40.862Z",
                "_tenantRef": "HOU",
                "tags": ["The Dream", "Hakeem the Dream Olajuwon"],
                "client_role": "Advisor"

            }